import os
import subprocess
import json
import glob
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import List, Optional

router = APIRouter(prefix="/api/automation", tags=["Automation Engine"])

class AutomationStep(BaseModel):
    id: int
    step: str
    action: str
    target: str
    value: Optional[str] = ""

class PlaybackRequest(BaseModel):
    steps: List[AutomationStep]
    browser: str
    device: str

@router.post("/run-playback")
def run_playback(payload: PlaybackRequest):
    """
    Executes the incoming test steps matrix via Node/Playwright,
    and returns the structured manifest.json log data.
    """
    # Guarantee Playwright executes them in the precise updated layout order.
    sorted_steps_list = sorted([step.dict() for step in payload.steps], key=lambda x: x['id'])
    
    # Encode the validated, ordered array to pass to Node
    steps_json = json.dumps(sorted_steps_list)
    
    try:
        # 🟩 BULLETPROOF DYNAMIC ROOT LOOKUP
        # Get the directory of this current file (e.g., .../backend/app/api)
        current_module_dir = os.path.dirname(os.path.abspath(__file__))
        
        # Break the absolute path into individual folder components based on the OS separator
        path_parts = current_module_dir.split(os.sep)
        
        # Explicitly look for the main workspace root directory name to lock onto
        if "AI_Automation_Tool" in path_parts:
            idx = path_parts.index("AI_Automation_Tool")
            # Splice path segments up to the root folder, stripping out trailing "backend" paths
            base_dir = os.sep.join(path_parts[:idx + 1])
        else:
            # Smart fallback logic if folder name varies on the client target machine
            base_dir = os.path.abspath(os.path.join(current_module_dir, "..", ".."))
            if os.path.basename(base_dir) == "backend":
                base_dir = os.path.abspath(os.path.join(base_dir, ".."))
        
        # Bind the path layers cleanly—now fully guaranteed to avoid the backend/frontend mashup!
        frontend_dir = os.path.join(base_dir, "frontend")
        script_path = os.path.join(frontend_dir, "runTask.js")
        
        print(f"🔍 Thread initiating Node task runner script at: {script_path}")
        
        # Enforce explicit UTF-8 environment variable mapping across process boundaries
        custom_env = os.environ.copy()
        custom_env["PYTHONIOENCODING"] = "utf-8"
        custom_env["NODE_CHANNEL_FD"] = "0"

        # Spawn the automation runner process
        process = subprocess.Popen(
            ["node", script_path, steps_json, payload.browser, payload.device],
            cwd=frontend_dir,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            encoding="utf-8",
            errors="ignore",
            env=custom_env
        )
        
        stdout, stderr = process.communicate()
        
        # Log terminal feedback to your local backend console stream
        if process.returncode == 0:
            print(f"🟩 Playwright Subprocess Completed Successfully.\n{stdout}")
        else:
            print(f"🟥 Playwright Subprocess Failed Execution.\n{stderr}")
            
        # 📂 FIND THE LATEST EVIDENCE PACKAGE MANIFEST
        evidence_base_path = os.path.join(frontend_dir, "playwright-evidence")
        run_folders = glob.glob(os.path.join(evidence_base_path, "run_*"))
        
        if not run_folders:
            raise HTTPException(status_code=500, detail="No evidence execution folders generated by runner loop.")
            
        # Grab the absolute newest timestamped execution directory path
        latest_run_dir = max(run_folders, key=os.path.getmtime)
        manifest_file_path = os.path.join(latest_run_dir, "manifest.json")
        
        # 🧠 SMART FIX: Wait for the OS to finish flushing the video asset to disk
        import time
        video_filename = None
        retries = 10  # Try 10 times
        
        for _ in range(retries):
            video_files = glob.glob(os.path.join(latest_run_dir, "*.webm"))
            if video_files:
                # Double check that the file size isn't 0 (still transferring bytes)
                if os.path.getsize(video_files[0]) > 0:
                    video_filename = os.path.basename(video_files[0])
                    print(f"🎥 Found finalized evidence video payload: {video_filename}")
                    break
            time.sleep(0.2)  # Pause 200ms between scans
        
        if not os.path.exists(manifest_file_path):
            raise HTTPException(status_code=500, detail="Manifest ledger mapping record missing from output tree.")
            
        # Read the perfect evidence log structure
        with open(manifest_file_path, "r", encoding="utf-8") as file:
            manifest_data = json.load(file)
            
        return {
            "success": True,
            "message": "Playback execution sequence finalized completely.",
            "run_id": os.path.basename(latest_run_dir),
            "video_filename": video_filename,
            "report": manifest_data
        }
        
    except Exception as e:
        print(f"❌ Automation controller breakdown sequence: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Internal Server Failure: {str(e)}")